name: learn-github-actions

# Define quando a ação será executada. Neste caso, em cada 'push'.
on: [push]

jobs:
  test-fastapi-app:
    # Define o sistema operacional do runner.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8",3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn[standard] pytest httpx pytest-asyncio

      - name: Run FastAPI app
        run: |
          uvicorn fastid.app:app --reload &
          sleep 5 # Aguarda a inicialização do servidor FastAPI

      - name: Run Pytest
        run: pytest -v
