name: learn-github-actions

# Define quando a ação será executada. Neste caso, em cada 'push'.
on: [push]

jobs:
  test-fastapi-app:
    # Define o sistema operacional do runner.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Pytest
        run:  poetry run pytest tests -v
